#!/bin/bash
loop=true;
figlet Pi - dcfldd;
echo "";
while $loop
 do
  read -e -p "pi-dcfldd > " arg;
  history -s "$arg";
  if [[ $arg = "q" || $arg = "e" || $arg = "exit" || $arg = "quit" ]]
  then
   loop=false;
  elif [[ $arg = "help" || $arg = "h" || $arg = "?" ]]
  then
   dcfldd -h;
  elif [[ $arg = "man" || $arg = "manual" ]]
  then
   man dcfldd;
  elif [[ ${arg%% *} = "cd" ]]
  then
   $arg;
  elif [[ $arg = "" ]]
  then
   echo -n; 
  elif which "${arg%% *}"
  then
   echo;
   echo "result:";
   $arg
  else
   sudo dcfldd $arg;
  fi	
 done
